# Generated by Django 5.0.1 on 2024-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
