# Generated by Django 5.0.1 on 2024-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_attendancereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
